####
# Splunk Savedsearches.conf Transformation Pipeline
# Only supports basic Windows and Sysmon logs.
####
transformations:
# Add winevent index to windows logs
  - id: index_condition
    type: add_condition
    conditions:
      index: winevent3
    rule_conditions:
      - type: logsource
        product: windows

postprocessing:
- type: template
  template: |+
    [{{ rule.title }} ]
    search = {{ query }} | eval rule_id="{{ rule.id }}", title="{{ rule.title }}", severity="{{rule.level}}"  | collect index=notable_events
    description = "{{ rule.description | replace('\n', ' ') }}"

finalizers:
- type: concat
  prefix: |
    [default]
    dispatch.earliest_time = -1y
    dispatch.latest_time = now
    enableSched = 1
    cron_schedule = */15 * * * *
    allow_skew = 5m
    alert.track = 1
    